---
# This playbook applys the baseline role to the test containers
- name: Fail if molecule group is missing
  hosts: localhost
  tasks:
    - name: Assert group existence
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}

- name: Apply the role to the testing containers (converge.yml)
  hosts: molecule
  vars_files:
    - "{{ lookup('env','HOME') }}/.site_data"
  tasks:
    - name: Include the role
      ansible.builtin.include_role:
        name: baseline
